affinity: {}
appConfig:
  appId: d879r1ddgg4s739hovs0
  appVersion: 1.0.0
  buildId: 72d0ad2dbca844a2b43ab62262709e97
  connectors: Google Cloud Storage-Google Sheets-Google Connection-General
  customFQImage: ""
  flogoAppMetrics: true
  flogoAppPropsEnv: auto
  flogoBaseImageTag: 2.26.4-b483
  flogoBuildTypeTag: 2.26.4-b483
  flogoExposeSwaggerEp: true
  flogoHttpServicePort: 7777
  lastUpdated: "1779343213"
  originalAppName: google_conn_tests
  tags: ""
  workloadType: user-app
appInit:
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: true
appProps:
  GoogleConnection.googleconn.Service_Account_Key: file:///etc/gcp/tci-flogo-5d1b86d38bf6.json
appSecrets: {}
auditSafe:
  enabled: true
autoscaling:
  behavior: {}
  customMetrics: []
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
crds: []
deploymentAnnotations: {}
deploymentLabels: {}
dpConfig:
  activationServiceUrl: ""
  capabilityDefaultNamespace: k8s-auto-dp1ns
  capabilityInstanceId: d85hkgp70q0s73em99dg
  capabilityVersion: 1.18.0
  customCertSecretName: ""
  dataplaneId: d81cvajkktgs73e2n0t0
  helmRepoAlias: tibco-platform-public
  licenseMountPath: /home/flogo/license
  licenseSecretName: cp-license-file-secret
  licenseSecretPath: /home/flogo/license/license-file.bin
enableTmpVolume: true
engineProps:
  FLOGO_LOG_LEVEL: ERROR
  FLOGO_OTEL_TRACE: "false"
engineSecrets: {}
executionHistory:
  enabled: false
flogoapp:
  envFrom:
    configMapRef: []
    secretRef: []
  envs: []
  lifecycle: {}
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /ping
      port: 7777
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 6
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /ping
      port: 7777
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: false
  startupProbe:
    failureThreshold: 50
    httpGet:
      path: /ping
      port: 7777
      scheme: HTTP
    periodSeconds: 6
    successThreshold: 1
    timeoutSeconds: 5
  volumeMounts:
  - mountPath: /etc/gcp
    name: mygconnvol
    readOnly: true
fluentBit:
  configMapName: otel-config-flogo
  enabled: true
  lifecycle: {}
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/v1/uptime
      port: 2020
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
fullnameOverride: google-conn-tests-helm
gateway:
  annotations: {}
  controllerName: ""
  enabled: false
  name: ""
  namespace: ""
  resourceInstanceName: ""
  rules:
  - host: example.com
    paths:
    - customCRDConfig: {}
      filters: []
      path: /
      pathType: PathPrefix
      port: 9999
      serviceDescription: ""
      serviceDiscoverable: true
  sectionName: ""
image:
  appInitImageName: tp-flogo-app-init
  appInitImageTag: "72"
  flogoBaseImageName: tp-flogo-app-base
  fluentBitImageName: common-fluentbit
  fluentBitImageTag: 5.0.5
  pullPolicy: IfNotPresent
  repository: csgprdusw2reposaas.jfrog.io/tibco-platform-docker-dev/
imagePullSecrets:
- name: d81cvajkktgs73e2n0t0
ingress:
  annotations: {}
  className: traefik
  controllerName: traefik
  enabled: true
  resourceInstanceName: ""
  rules:
  - host: apps-traefik.cp1-my.localhost.dataplanes.pro
    paths:
    - path: /tibco/apps/d879r1ddgg4s739hovs0/ReceiveHTTPMessage
      pathType: Prefix
      port: 9999
      serviceDescription: '{"services":[{"specURL":"https://apps-traefik.cp1-my.localhost.dataplanes.pro/tibco/apps/d879r1ddgg4s739hovs0/ReceiveHTTPMessage/api/v2/swagger.json","serviceURL":"https://apps-traefik.cp1-my.localhost.dataplanes.pro/tibco/apps/d879r1ddgg4s739hovs0/ReceiveHTTPMessage","title":"google_conn_tests","description":"google_conn_tests
        service"}]}'
      serviceDiscoverable: true
  tls: []
initContainers: []
nameOverride: ""
networkPolicy:
  clusterEgress: enable
  databaseEgress: enable
  internetAll: enable
  internetWeb: enable
  msgInfra: enable
  proxyEgress: enable
  userApps: enable
nodeSelector: {}
otel:
  metrics:
    enabled: true
  traces:
    enabled: true
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: Always
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
pvc: []
replicaCount: 1
service:
  annotations: {}
  customhealthCheckPolicy: {}
  labels: {}
  ports:
  - port: "9999"
    targetPort: "9999"
  serviceDescription: '{"services":[{"specURL":"http://google-conn-tests.k8s-auto-dp1ns.svc.cluster.local:9999/api/v2/swagger.json","serviceURL":"http://google-conn-tests.k8s-auto-dp1ns.svc.cluster.local:9999","title":"ReceiveHTTPMessage","description":"ReceiveHTTPMessage
    service"}]}'
  serviceDiscoverable: true
  type: ClusterIP
serviceAccountName: ""
serviceMesh:
  enabled: false
sidecars: []
strategy:
  type: RollingUpdate
tolerations: []
topologySpreadConstraints: []
volumes:
- name: mygconnvol
  secret:
    optional: false
    secretName: gcs-sa-key
workload: deployment
